import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

const translations = {
  en: {
    dashboard: 'Dashboard',
    members: 'Members',
    events: 'Events',
    gallery: 'Gallery',
    announcements: 'Announcements',
    myProfile: 'My Profile',
    adminPanel: 'Admin Panel',
    signOut: 'Sign Out',
    jaiHanuman: 'Jai Hanuman',
    welcome: 'Welcome',
    bhaktha: 'Bhaktha',
    youthMembers: 'Youth Members',
    upcomingEvents: 'Upcoming Events',
    latestAnnouncements: 'Latest Announcements',
    viewAll: 'View All',
    supportSeva: 'Support Our Seva & Temple Renovation',
    copyUPI: 'Copy UPI ID',
    bankTransfer: 'Direct Bank Transfer',
    galleryHighlights: 'Gallery Highlights',
    fullName: 'Full Name',
    roleDesignation: 'Role/Designation',
    phoneNumber: 'Phone Number',
    villageArea: 'Village Area / Street',
    memberPhoto: 'Member Photo',
    chooseImage: 'Choose Image',
    orUseUrl: 'or use URL',
    saveMember: 'Save Member',
    cancel: 'Cancel',
    editProfile: 'Edit Profile',
    password: 'Password',
    emailAddress: 'Email Address',
    contactNumber: 'Contact Number',
    address: 'Village / Address',
    adminAccess: 'Administrative Access',
    adminAccessDesc: 'Enabled. You can edit database entries.',
    newAnnouncement: 'New Announcement',
    title: 'Title',
    messageContent: 'Message Content *',
    publishNow: 'Publish Now',
    activeYouthDesc: 'Active youth working towards community development',
    importantUpdates: 'Important updates, notices, and communications for the youth',
    addMemberBtn: 'Add Member',
    editMemberDetails: 'Edit Member Details',
    searchPlaceholder: 'Search by name, role, or area...',
    noMembersFound: 'No members found matching your search.',
    publishAnnouncement: 'Publish Announcement',
    notifications: 'Notifications',
    noNotifications: 'No notifications yet.',
    markAsRead: 'Mark as read',
    viewAllNotifications: 'View All Announcements',
    saveDetails: 'Save Details',
    choosePhoto: 'Choose Photo',
    remove: 'Remove',
    jaiHanumanDesc: '"Sri Anjaneya Youth Zarugumalli" is united to serve the community, celebrate our cultural roots, and drive positive progress in Zarugumalli.',
    sevaDesc: 'Contribute towards community meals, education kits, and festival events',
    sevaLongDesc: 'We regularly organize Annadanam (food distributions), support underprivileged school students with study kits, manage blood donation drives, and help coordinate festivals at the Sri Anjaneya Swamy Temple. Your generosity drives this change.',
    newPassword: 'New Password (min 6 chars) *',
    confirmNewPassword: 'Confirm New Password *',
    updatePassword: 'Update Password',
    changePassword: 'Change Password',
    enterNewPassword: 'Enter new password',
    confirmPasswordPlaceholder: 'Confirm new password',
    aboutUs: 'About Us',
    quickLinks: 'Quick Links',
    footerCredits: 'Developed by Ganesh Nalamalapu',
    footerRights: 'All Rights Reserved.',
    footerTemple: 'Sri Anjaneya Swamy Devastanam',
    donationAlert: 'Donation details copied! Direct UPI: anjaneyayouth@sbi',
    loadingDashboard: 'Loading Dashboard...',
    loadingAnnouncements: 'Loading announcements...',
    loadingMembers: 'Loading members list...',
    zarugumalli: 'Zarugumalli',
    websiteName: 'Sri Anjaneya Youth',
    joinWebsiteName: 'Join Sri Anjaneya Youth',
    associationSubtitle: 'Zarugumalli Youth Association',
    associationGallery: 'Association Gallery',
    gallerySubtitle: 'Visual moments of our services, festivals, and temple events',
    uploadPhoto: 'Upload Photo',
    loadingGallery: 'Loading gallery...',
    noGalleryItems: 'No gallery items found in this category.',
    uploadPhotoTitle: 'Upload Association Photo',
    imagePresetLabel: 'Or choose a preset devotional image:',
    categoryLabel: 'Category *',
    captionLabel: 'Caption / Description *',
    captionPlaceholder: 'Describe the moment captured...',
    savePhoto: 'Save Photo',
    deletePhotoConfirm: 'Are you sure you want to remove this photo from the gallery?',
    failedDeletePhoto: 'Failed to delete image.',
    failedSavePhoto: 'Failed to save photo.',
    fillAllDetails: 'Please fill in all details.',
    uploadedOn: 'Uploaded on',
    templeEvents: 'Temple Events',
    festivals: 'Festivals',
    serviceSeva: 'Service / Seva',
    all: 'All',
    committeeMembership: 'Committee Membership',
    requestCommitteeBtn: 'Request Committee Membership',
    committeePendingStatus: 'Your request is pending admin approval.',
    committeeApprovedStatus: 'You are an approved Committee Member!',
    committeeRequestSent: 'Request sent successfully!',
    associationMembers: 'Association Members',
    redirectUrlLabel: 'Redirect Link (Optional)',
    redirectUrlPlaceholder: 'https://example.com/more-info or video link',
    aboutUsTitle: 'About Our Association',
    aboutPara1: 'Founded by enthusiastic youngsters of Zarugumalli Village, the association serves under the patronage of Sri Anjaneya Swamy.',
    aboutPara2: 'Our core mission revolves around three pillars: Seva (social service), Culture (preservation of traditional celebrations), and Community (building harmony and supporting village development).',
    aboutPara3: 'We conduct regular activities like maintaining public cleanliness, coordinating local festival processions, helping in emergency services, and assisting during temple celebrations.',
    reachUsTitle: 'Reach Us',
    officeAddressLabel: 'Office Address',
    officeAddressVal: 'Sri Anjaneya Youth Hall, Near Ramalayam Temple, Zarugumalli Village, Prakasam Dist, Andhra Pradesh - 523274',
    callCoordinatorLabel: 'Call President / Coordinator',
    emailSupportLabel: 'Email Support',
    contactAssociation: 'Contact Association',
    footerAddressVal: 'Sri Anjaneya Youth Association, Zarugumalli Village, Prakasam District, Andhra Pradesh - 523274',
    unitedQuote: 'United for Seva, Culture, and Community',
    donate: 'Donate',
    donations: 'Donations',
    donorName: 'Donor Name *',
    donorNamePlaceholder: 'Enter your full name',
    mobileNumber: 'Mobile Number *',
    mobileNumberPlaceholder: 'Enter 10-digit mobile number',
    emailAddressOptional: 'Email Address (Optional)',
    emailAddressPlaceholder: 'name@domain.com',
    donationAmount: 'Donation Amount (₹) *',
    donationAmountPlaceholder: 'Enter amount to donate',
    paymentMethod: 'Payment Method *',
    selectMethod: 'Select payment method',
    donationPurpose: 'Message / Purpose of Donation',
    donationPurposePlaceholder: 'e.g., Annadanam, Temple Renovation, General Fund',
    donateNowBtn: 'Donate Now',
    paymentSuccess: 'Payment Successful',
    paymentFailed: 'Payment Failed',
    paymentPending: 'Payment Pending',
    thankYouDonation: 'Thank you for your generous contribution! May Sri Anjaneya Swamy bless you.',
    paymentErrorMsg: 'Your transaction could not be processed. Please try again.',
    paymentPendingMsg: 'Your payment is under verification. We will update the status shortly.',
    totalDonations: 'Total Donations',
    searchDonors: 'Search donors by name, email, or transaction ID...',
    filterStatus: 'Filter Status',
    allStatuses: 'All Statuses',
    dateAndTime: 'Date & Time',
    transactionId: 'Transaction ID / Payment ID',
    noDonations: 'No donations found.',
    donationsDashboardDesc: 'Total contributions received from our generous donors',
    numberDonations: 'Number of Donations',
    totalAmountDonated: 'Total Amount Donated',
    hanumanShlokaPart1: 'Manojavam Marutatulyavegam, Jitendriyam Buddhimatam Varishtham.',
    hanumanShlokaPart2: 'Vatatmajam Vanarayuthamukhyam, Sriramadutam Sharanam Prapadye.',
    purposeGeneral: 'General Fund / General Seva',
    purposeAnnadanam: 'Hanuman Jayanthi Annadanam',
    purposeRenovation: 'Temple Devastanam Renovation',
    purposeEducation: 'Village Children Education Support',
    bhimUpiQr: 'BHIM UPI / QR',
    upiApps: 'GPay, PhonePe, Paytm',
    creditDebitCard: 'Credit / Debit Card',
    cardBrands: 'Visa, MasterCard, Rupay',
    netBanking: 'Net Banking',
    bankList: 'SBI, HDFC, ICICI, etc.',
    signInTitle: 'Sign In',
    forgotPassword: 'Forgot Password?',
    passwordPlaceholder: '••••••••',
    signInBtn: 'Sign In',
    signUpRedirectText: 'New user?',
    signUpRedirectLink: 'Create an account',
    mockAccountsText: 'Mock Accounts Available:',
    installAppBtn: 'Install / Download App',
    emailAddressLabel: 'Email Address',
    passwordLabel: 'Password',
    signUpTitle: 'Register Account',
    fullNameLabel: 'Full Name',
    fullNamePlaceholder: 'Enter your full name',
    phoneNumberLabel: 'Phone Number',
    phoneNumberPlaceholder: '+91 98765 43210',
    villageAreaLabel: 'Village / Area',
    villageAreaPlaceholder: 'e.g. Ramalayam Street, Zarugumalli',
    confirmPasswordLabel: 'Confirm Password',
    signUpBtn: 'Register Account',
    signInRedirectText: 'Already have an account?',
    signInRedirectLink: 'Sign In here',
    continueWithGoogle: 'Continue with Google',
    signUpWithGoogle: 'Sign up with Google',
    or: 'Or',
    developedBy: 'Developed by',
    sendOtp: 'Send OTP',
    verifyOtp: 'Verify OTP',
    otpLabel: 'Verification Code (OTP)'
  },
  te: {
    zarugumalli: 'జరుగమల్లి',
    websiteName: 'శ్రీ ఆంజనేయ యూత్',
    joinWebsiteName: 'శ్రీ ఆంజనేయ యూత్ లో చేరండి',
    associationSubtitle: 'జరుగమల్లి యువజన సంఘం',
    associationGallery: 'సంఘం గ్యాలరీ',
    gallerySubtitle: 'మా సేవలు, పండుగలు మరియు ఆలయ కార్యక్రమాల దృశ్యాలు',
    uploadPhoto: 'ఫోటో అప్‌లోడ్ చేయి',
    loadingGallery: 'గ్యాలరీ లోడ్ అవుతోంది...',
    noGalleryItems: 'ఈ వర్గంలో గ్యాలరీ చిత్రాలు ఏవీ లేవు.',
    uploadPhotoTitle: 'సంఘం ఫోటోను అప్‌లోడ్ చేయి',
    imagePresetLabel: 'లేదా ఏదైనా భక్తి చిత్రాన్ని ఎంచుకోండి:',
    categoryLabel: 'వర్గం *',
    captionLabel: 'శీర్షిక / వివరణ *',
    captionPlaceholder: 'చిత్రం యొక్క వివరణను వ్రాయండి...',
    savePhoto: 'ఫోటో సేవ్ చేయి',
    deletePhotoConfirm: 'ఈ ఫోటోను గ్యాలరీ నుండి తొలగించాలనుకుంటున్నారా?',
    failedDeletePhoto: 'చిత్రాన్ని తొలగించడంలో విఫలమైంది.',
    failedSavePhoto: 'ఫోటోను సేవ్ చేయడంలో విఫలమైంది.',
    fillAllDetails: 'దయచేసి అన్ని వివరాలను పూరించండి.',
    uploadedOn: 'అప్‌లోడ్ చేసిన తేదీ',
    templeEvents: 'ఆలయ కార్యక్రమాలు',
    festivals: 'పండుగలు',
    serviceSeva: 'సేవా కార్యక్రమాలు',
    all: 'అన్నీ',
    committeeMembership: 'కమిటీ సభ్యత్వం',
    requestCommitteeBtn: 'కమిటీ సభ్యత్వం కోసం అభ్యర్థించండి',
    committeePendingStatus: 'మీ అభ్యర్థన అడ్మిన్ ఆమోదం కోసం పెండింగ్‌లో ఉంది.',
    committeeApprovedStatus: 'మీరు ఆమోదించబడిన కమిటీ సభ్యులు!',
    committeeRequestSent: 'అభ్యర్థన విజయవంతంగా పంపబడింది!',
    associationMembers: 'సంఘ సభ్యులు',
    dashboard: 'డాష్‌బోర్డ్',
    members: 'సభ్యులు',
    events: 'కార్యక్రమాలు',
    gallery: 'గ్యాలరీ',
    announcements: 'ప్రకటనలు',
    myProfile: 'నా ప్రొఫైల్',
    adminPanel: 'అడ్మిన్ ప్యానెల్',
    signOut: 'లాగ్ అవుట్',
    jaiHanuman: 'జై హనుమాన్',
    welcome: 'స్వాగతం',
    bhaktha: 'భక్తుడు',
    youthMembers: 'యువ సభ్యులు',
    upcomingEvents: 'రాబోయే కార్యక్రమాలు',
    latestAnnouncements: 'తాజా ప్రకటనలు',
    viewAll: 'అన్నీ చూడండి',
    supportSeva: 'మా సేవ & ఆలయ పునరుద్ధరణకు మద్దతు ఇవ్వండి',
    copyUPI: 'UPI ఐడీ కాపీ చేయి',
    bankTransfer: 'డైరెక్ట్ బ్యాంక్ బదిలీ',
    galleryHighlights: 'గ్యాలరీ ముఖ్యాంశాలు',
    fullName: 'పూర్తి పేరు',
    roleDesignation: 'హోదా / బాధ్యత',
    phoneNumber: 'ఫోన్ నంబర్',
    villageArea: 'గ్రామ ప్రాంతం / వీధి',
    memberPhoto: 'సభ్యుని ఫోటో',
    chooseImage: 'చిత్రాన్ని ఎంచుకోండి',
    orUseUrl: 'లేదా URL ఉపయోగించండి',
    saveMember: 'సభ్యుడిని సేవ్ చేయి',
    cancel: 'రద్దు చేయి',
    editProfile: 'ప్రొఫైల్ సవరించు',
    password: 'పాస్‌వర్డ్',
    emailAddress: 'ఈమెయిల్ చిరునామా',
    contactNumber: 'సంప్రదింపు సంఖ్య',
    address: 'చిరునామా / గ్రామం',
    adminAccess: 'అడ్మినిస్ట్రేటివ్ యాక్సెస్',
    adminAccessDesc: 'యాక్సెస్ ఉంది. మీరు డేటాబేస్ ఎంట్రీలను సవరించవచ్చు.',
    newAnnouncement: 'కొత్త ప్రకటన',
    title: 'శీర్షిక',
    messageContent: 'సందేశ కంటెంట్ *',
    publishNow: 'ప్రకటించు',
    activeYouthDesc: 'గ్రామ అభివృద్ధి కోసం పనిచేస్తున్న క్రియాశీల యువత',
    importantUpdates: 'యువతకు ముఖ్యమైన నవీకరణలు మరియు నోటీసులు',
    addMemberBtn: 'సభ్యుడిని చేర్చు',
    editMemberDetails: 'సభ్యుని వివరాలను సవరించు',
    searchPlaceholder: 'పేరు, బాధ్యత లేదా ప్రాంతం ద్వారా వెతకండి...',
    noMembersFound: 'వెతికిన దానికి సరిపోయే సభ్యులు ఎవరూ లేరు.',
    publishAnnouncement: 'ప్రకటనను ప్రచురించు',
    notifications: 'నోటిఫికేషన్లు',
    noNotifications: 'నోటిఫికేషన్‌లు లేవు.',
    markAsRead: 'చదివినట్లుగా గుర్తుపెట్టు',
    viewAllNotifications: 'అన్ని ప్రకటనలు చూడండి',
    saveDetails: 'వివరాలు సేవ్ చేయి',
    choosePhoto: 'ఫోటో ఎంచుకోండి',
    remove: 'తొలగించు',
    jaiHanumanDesc: '"శ్రీ ఆంజనేయ యూత్ జరుగమల్లి" మన గ్రామంలో సేవ చేయడానికి, సంస్కృతిని కాపాడుకోవడానికి మరియు అభివృద్ధిని ప్రోత్సహించడానికి ఐక్యమైంది.',
    sevaDesc: 'ఉచిత అన్నదానాలు, విద్యా సామగ్రి పంపిణీ మరియు దేవాలయ ఉత్సవాలకు సహాయపడండి',
    sevaLongDesc: 'మేము క్రమం తప్పకుండా అన్నదానం, వెనుకబడిన విద్యార్థులకు విద్యా కిట్లు పంపిణీ చేయడం, రక్తదాన శిబిరాలు నిర్వహించడం మరియు శ్రీ ఆంజనేయ స్వామి ఆలయంలో ఉత్సవాల సమన్వయానికి సహాయం చేస్తుంటాము. మీ సహాయం ఈ మార్పునకు కారణమవుతుంది.',
    newPassword: 'కొత్త పాస్‌వర్డ్ (కనీసం 6 అక్షరాలు) *',
    confirmNewPassword: 'కొత్త పాస్‌వర్డ్ నిర్ధారించండి *',
    updatePassword: 'పాస్‌వర్డ్ నవీకరించు',
    changePassword: 'పాస్‌వర్డ్ మార్చు',
    enterNewPassword: 'కొత్త పాస్‌వర్డ్ నమోదు చేయండి',
    confirmPasswordPlaceholder: 'కొత్త పాస్‌వర్డ్ నిర్ధారించండి',
    aboutUs: 'మా గురించి',
    quickLinks: 'త్వరిత లింకులు',
    footerCredits: 'రూపకల్పన: గణేష్ నలమలపు',
    footerRights: 'అన్ని హక్కులు ప్రత్యేకించబడ్డాయి.',
    footerTemple: 'శ్రీ ఆంజనేయ స్వామి దేవస్థానం',
    donationAlert: 'విరాళం వివరాలు కాపీ చేయబడ్డాయి! UPI: anjaneyayouth@sbi',
    loadingDashboard: 'డాష్‌బోర్డ్ లోడ్ అవుతోంది...',
    loadingAnnouncements: 'ప్రకటనలు లోడ్ అవుతున్నాయి...',
    loadingMembers: 'సభ్యుల జాబితా లోడ్ అవుతోంది...',
    redirectUrlLabel: 'రీడైరెక్ట్ లింక్ (ఐచ్ఛికం)',
    redirectUrlPlaceholder: 'https://example.com/more-info లేదా వీడియో లింక్',
    aboutUsTitle: 'మా సంఘం గురించి',
    aboutPara1: 'జరుగమల్లి గ్రామ ఉత్సాహవంతులైన యువకులు స్థాపించిన ఈ సంఘం, శ్రీ ఆంజనేయ స్వామి వారి ఆశీస్సులతో సేవలను అందిస్తోంది.',
    aboutPara2: 'మా ప్రధాన లక్ష్యం మూడు స్తంభాలపై ఆధారపడి ఉంటుంది: సేవ (సామాజిక సేవ), సంస్కృతి (సాంప్రదాయ ఉత్సవాల పరిరక్షణ), మరియు సంఘం (సమైక్యతను పెంపొందించడం మరియు గ్రామ అభివృద్ధికి తోడ్పడడం).',
    aboutPara3: 'మేము గ్రామంలో పరిశుభ్రత కార్యక్రమాలు, స్థానిక పండుగల ఊరేగింపులు, అత్యవసర సేవలు మరియు దేవాలయ ఉత్సవాలలో సహాయం చేయడం వంటి నిరంతర కార్యక్రమాలను నిర్వహిస్తాము.',
    reachUsTitle: 'మమ్మల్ని సంప్రదించండి',
    officeAddressLabel: 'కార్యాలయ చిరునామా',
    officeAddressVal: 'శ్రీ ఆంజనేయ యూత్ హాల్, రామాలయం గుడి దగ్గర, జరుగమల్లి గ్రామం, ప్రకాశం జిల్లా, ఆంధ్రప్రదేశ్ - 523274',
    callCoordinatorLabel: 'ప్రెసిడెంట్ / కోఆర్డినేటర్‌ను సంప్రదించండి',
    emailSupportLabel: 'ఈమెయిల్ మద్దతు',
    contactAssociation: 'సంఘాన్ని సంప్రదించండి',
    footerAddressVal: 'శ్రీ ఆంజనేయ యూత్ అసోసియేషన్, జరుగమల్లి గ్రామం, ప్రకాశం జిల్లా, ఆంధ్రప్రదేశ్ - 523274',
    unitedQuote: 'సేవ, సంస్కృతి మరియు సమాజం కోసం ఐక్యమయ్యాము',
    donate: 'విరాళం ఇవ్వండి',
    donations: 'విరాళాలు',
    donorName: 'దాత పేరు *',
    donorNamePlaceholder: 'మీ పూర్తి పేరు నమోదు చేయండి',
    mobileNumber: 'మొబైల్ సంఖ్య *',
    mobileNumberPlaceholder: '10 అంకెల మొబైల్ సంఖ్యను నమోదు చేయండి',
    emailAddressOptional: 'ఈమెయిల్ చిరునామా (ఐచ్ఛికం)',
    emailAddressPlaceholder: 'name@domain.com',
    donationAmount: 'విరాళం మొత్తం (₹) *',
    donationAmountPlaceholder: 'విరాళం మొత్తం నమోదు చేయండి',
    paymentMethod: 'చెల్లింపు విధానం *',
    selectMethod: 'చెల్లింపు విధానాన్ని ఎంచుకోండి',
    donationPurpose: 'విరాళం యొక్క ఉద్దేశం / సందేశం',
    donationPurposePlaceholder: 'ఉదా: అన్నదానం, ఆలయ పునరుద్ధరణ, సాధారణ నిధి',
    donateNowBtn: 'ఇప్పుడే విరాళం ఇవ్వండి',
    paymentSuccess: 'చెల్లింపు విజయవంతమైంది',
    paymentFailed: 'చెల్లింపు విఫలమైంది',
    paymentPending: 'చెల్లింపు పెండింగ్‌లో ఉంది',
    thankYouDonation: 'మీ ఉదార విరాళానికి ధన్యవాదాలు! శ్రీ ఆంజనేయ స్వామి వారి ఆశీస్సులు మీకు ఎల్లప్పుడూ ఉండాలని కోరుకుంటున్నాము.',
    paymentErrorMsg: 'మీ లావాదేవీని పూర్తి చేయలేకపోయాము. దయచేసి మళ్లీ ప్రయత్నించండి.',
    paymentPendingMsg: 'మీ చెల్లింపు ధృవీకరణలో ఉంది. మేము త్వరలో స్థితిని నవీకరిస్తాము.',
    totalDonations: 'మొత్తం విరాళాలు',
    searchDonors: 'దాత పేరు, ఈమెయిల్ లేదా లావాదేవీ ID ద్వారా వెతకండి...',
    filterStatus: 'చెల్లింపు స్థితి ఫిల్టర్',
    allStatuses: 'అన్ని స్థితులు',
    dateAndTime: 'తేదీ & సమయం',
    transactionId: 'లావాదేవీ ID / చెల్లింపు ID',
    noDonations: 'విరాళాలు ఏవీ లేవు.',
    donationsDashboardDesc: 'మా దాతల నుండి సేకరించిన మొత్తం విరాళాలు',
    numberDonations: 'విరాళాల సంఖ్య',
    totalAmountDonated: 'మొత్తం సేకరించిన విరాళాలు',
    hanumanShlokaPart1: 'మనోజవం మారుతతుల్యవేగం, జితేంద్రియం బుద్ధిమతాం వరిష్ఠమ్.',
    hanumanShlokaPart2: 'వాతాత్మజం వానరయూథముఖ్యం, శ్రీరామదూతం శరణం ప్రపద్యే.',
    purposeGeneral: 'సాధారణ నిధి / సాధారణ సేవ',
    purposeAnnadanam: 'హనుమాన్ జయంతి అన్నదానం',
    purposeRenovation: 'దేవాలయ పునరుద్ధరణ',
    purposeEducation: 'గ్రామ పిల్లల విద్యా సహాయం',
    bhimUpiQr: 'BHIM UPI / QR కోడ్',
    upiApps: 'GPay, PhonePe, Paytm',
    creditDebitCard: 'క్రెడిట్ / డెబిట్ కార్డ్',
    cardBrands: 'వీసా, మాస్టర్ కార్డ్, రూపే',
    netBanking: 'నెట్ బ్యాంకింగ్',
    bankList: 'SBI, HDFC, ICICI, మొదలైనవి',
    signInTitle: 'లాగిన్',
    forgotPassword: 'పాస్‌వర్డ్ మర్చిపోయారా?',
    passwordPlaceholder: '••••••••',
    signInBtn: 'లాగిన్ చేయి',
    signUpRedirectText: 'కొత్త యూజరా?',
    signUpRedirectLink: 'ఖాతాను సృష్టించండి',
    mockAccountsText: 'డెమో ఖాతాల వివరాలు:',
    installAppBtn: 'యాప్ డౌన్‌లోడ్ చేయండి',
    emailAddressLabel: 'ఈమెయిల్ చిరునామా',
    passwordLabel: 'పాస్‌వర్డ్',
    signUpTitle: 'ఖాతాను సృష్టించండి',
    fullNameLabel: 'పూర్తి పేరు',
    fullNamePlaceholder: 'మీ పూర్తి పేరు నమోదు చేయండి',
    phoneNumberLabel: 'ఫోన్ నంబర్',
    phoneNumberPlaceholder: '+91 98765 43210',
    villageAreaLabel: 'గ్రామం / ప్రాంతం',
    villageAreaPlaceholder: 'ఉదా: రామాలయం వీధి, జరుగమల్లి',
    confirmPasswordLabel: 'పాస్‌వర్డ్ నిర్ధారించండి',
    signUpBtn: 'నమోదు చేయి',
    signInRedirectText: 'ఇప్పటికే ఖాతా ఉందా?',
    signInRedirectLink: 'ఇక్కడ లాగిన్ అవ్వండి',
    continueWithGoogle: 'Google తో లాగిన్ అవ్వండి',
    signUpWithGoogle: 'Google తో సైన్ అప్ అవ్వండి',
    or: 'లేదా',
    developedBy: 'రూపకల్పన:',
    sendOtp: 'OTP పంపండి',
    verifyOtp: 'OTP ధృవీకరించండి',
    otpLabel: 'ధృవీకరణ కోడ్ (OTP)'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('sa_language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('sa_language', language);
    // Dynamically update document/tab title in Telugu/English
    document.title = language === 'en' 
      ? 'Sri Anjaneya Youth Zarugumalli' 
      : 'శ్రీ ఆంజనేయ యూత్ జరుగమల్లి';
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
