import { createContext, useContext, useState, useEffect } from 'react';
import {
  translateName,
  translateRole,
  translateAddress,
  translateStatus,
  translatePurpose,
  translateText
} from '../utils/teluguTransliterate';

// Re-export transliteration helpers for direct use anywhere
export {
  translateName,
  translateRole,
  translateAddress,
  translateStatus,
  translatePurpose,
  translateText
};

const LanguageContext = createContext(null);

export const translations = {
  en: {
    "dashboard": "Dashboard",
    "members": "Members",
    "events": "Events",
    "gallery": "Gallery",
    "announcements": "Announcements",
    "myProfile": "My Profile",
    "adminPanel": "Admin Panel",
    "signOut": "Sign Out",
    "logout": "Sign Out",
    "jaiHanuman": "Jai Hanuman",
    "welcome": "Welcome",
    "bhaktha": "Bhaktha",
    "youthMembers": "Youth Members",
    "upcomingEvents": "Upcoming Events",
    "latestAnnouncements": "Latest Announcements",
    "viewAll": "View All",
    "supportSeva": "Support Our Seva & Temple Renovation",
    "copyUPI": "Copy UPI ID",
    "bankTransfer": "Direct Bank Transfer",
    "galleryHighlights": "Gallery Highlights",
    "fullName": "Full Name",
    "roleDesignation": "Role/Designation",
    "phoneNumber": "Phone Number",
    "villageArea": "Village Area / Street",
    "memberPhoto": "Member Photo",
    "chooseImage": "Choose Image",
    "orUseUrl": "or use URL",
    "saveMember": "Save Member",
    "cancel": "Cancel",
    "editProfile": "Edit Profile",
    "password": "Password",
    "emailAddress": "Email Address",
    "contactNumber": "Contact Number",
    "address": "Village / Address",
    "adminAccess": "Administrative Access",
    "adminAccessDesc": "Enabled. You can edit database entries.",
    "newAnnouncement": "New Announcement",
    "title": "Title",
    "messageContent": "Message Content *",
    "publishNow": "Publish Now",
    "activeYouthDesc": "Active youth working towards community development",
    "importantUpdates": "Important updates, notices, and communications for the youth",
    "addMemberBtn": "Add Member",
    "editMemberDetails": "Edit Member Details",
    "searchPlaceholder": "Search by name, role, or area...",
    "noMembersFound": "No members found matching your search.",
    "publishAnnouncement": "Publish Announcement",
    "notifications": "Notifications",
    "noNotifications": "No notifications yet.",
    "markAsRead": "Mark as read",
    "viewAllNotifications": "View All Announcements",
    "saveDetails": "Save Details",
    "choosePhoto": "Choose Photo",
    "remove": "Remove",
    "jaiHanumanDesc": "“Sri Anjaneya Youth Zarugumalli” is united to serve the community, celebrate our cultural roots, and drive positive progress in Zarugumalli.",
    "sevaDesc": "Contribute towards community meals, education kits, and festival events",
    "sevaLongDesc": "We regularly organize Annadanam (food distributions), support underprivileged school students with study kits, manage blood donation drives, and help coordinate festivals at the Sri Anjaneya Swamy Temple. Your generosity drives this change.",
    "newPassword": "New Password (min 6 chars) *",
    "confirmNewPassword": "Confirm New Password *",
    "updatePassword": "Update Password",
    "changePassword": "Change Password",
    "enterNewPassword": "Enter new password",
    "confirmPasswordPlaceholder": "Confirm new password",
    "aboutUs": "About Us",
    "quickLinks": "Quick Links",
    "footerCredits": "Developed by Ganesh Nalamalapu",
    "footerRights": "All Rights Reserved.",
    "footerTemple": "Sri Anjaneya Swamy Devastanam",
    "donationAlert": "Donation details copied! Direct UPI: anjaneyayouth@sbi",
    "loadingDashboard": "Loading Dashboard...",
    "loadingAnnouncements": "Loading announcements...",
    "loadingMembers": "Loading members list...",
    "zarugumalli": "Zarugumalli",
    "websiteName": "Sri Anjaneya Youth",
    "joinWebsiteName": "Join Sri Anjaneya Youth",
    "associationSubtitle": "Zarugumalli Youth Association",
    "associationGallery": "Association Gallery",
    "gallerySubtitle": "Visual moments of our services, festivals, and temple events",
    "uploadPhoto": "Upload Photo",
    "loadingGallery": "Loading gallery...",
    "noGalleryItems": "No gallery items found in this category.",
    "uploadPhotoTitle": "Upload Association Photo",
    "imagePresetLabel": "Or choose a preset devotional image:",
    "categoryLabel": "Category *",
    "captionLabel": "Caption / Description *",
    "captionPlaceholder": "Describe the moment captured...",
    "savePhoto": "Save Photo",
    "deletePhotoConfirm": "Are you sure you want to remove this photo from the gallery?",
    "failedDeletePhoto": "Failed to delete image.",
    "failedSavePhoto": "Failed to save photo.",
    "fillAllDetails": "Please fill in all details.",
    "uploadedOn": "Uploaded on",
    "templeEvents": "Temple Events",
    "festivals": "Festivals",
    "serviceSeva": "Service / Seva",
    "galleryAlbums": "Gallery Albums",
    "noGalleryAlbums": "No gallery albums found.",
    "photosCount": "Photos",
    "eventDateLabel": "Event Date *",
    "shortDescLabel": "Short Description *",
    "coverImageLabel": "Cover Image *",
    "albumImagesLabel": "Album Images",
    "saveAlbum": "Save Album",
    "createAlbum": "Create Album",
    "editAlbum": "Edit Album",
    "titleLabel": "Gallery Title *",
    "all": "All",
    "committeeMembership": "Committee Membership",
    "requestCommitteeBtn": "Request Committee Membership",
    "committeePendingStatus": "Your request is pending admin approval.",
    "committeeApprovedStatus": "You are an approved Committee Member!",
    "committeeRequestSent": "Request sent successfully!",
    "associationMembers": "Association Members",
    "redirectUrlLabel": "Redirect Link (Optional)",
    "redirectUrlPlaceholder": "https://example.com/more-info or video link",
    "aboutUsTitle": "About Our Association",
    "aboutPara1": "Founded by enthusiastic youngsters of Zarugumalli Village, the association serves under the patronage of Sri Anjaneya Swamy.",
    "aboutPara2": "Our core mission revolves around three pillars: Seva (social service), Culture (preservation of traditional celebrations), and Community (building harmony and supporting village development).",
    "aboutPara3": "We conduct regular activities like maintaining public cleanliness, coordinating local festival processions, helping in emergency services, and assisting during temple celebrations.",
    "reachUsTitle": "Reach Us",
    "officeAddressLabel": "Office Address",
    "officeAddressVal": "Sri Anjaneya Youth Hall, Near Ramalayam Temple, Zarugumalli Village, Prakasam Dist, Andhra Pradesh - 523274",
    "callCoordinatorLabel": "Call President / Coordinator",
    "emailSupportLabel": "Email Support",
    "contactAssociation": "Contact Association",
    "footerAddressVal": "Sri Anjaneya Youth Association, Zarugumalli Village, Prakasam District, Andhra Pradesh - 523274",
    "unitedQuote": "United for Seva, Culture, and Community",
    "donate": "Donate",
    "donations": "Donations",
    "donorName": "Donor Name *",
    "donorNamePlaceholder": "Enter your full name",
    "mobileNumber": "Mobile Number *",
    "mobileNumberPlaceholder": "Enter 10-digit mobile number",
    "emailAddressOptional": "Email Address (Optional)",
    "emailAddressPlaceholder": "name@domain.com",
    "donationAmount": "Donation Amount (₹) *",
    "donationAmountPlaceholder": "Enter amount to donate",
    "paymentMethod": "Payment Method *",
    "selectMethod": "Select payment method",
    "donationPurpose": "Message / Purpose of Donation",
    "donationPurposePlaceholder": "e.g., Annadanam, Temple Renovation, General Fund",
    "donateNowBtn": "Donate Now",
    "paymentSuccess": "Payment Successful",
    "paymentFailed": "Payment Failed",
    "paymentPending": "Payment Pending",
    "thankYouDonation": "Thank you for your generous contribution! May Sri Anjaneya Swamy bless you.",
    "paymentErrorMsg": "Your transaction could not be processed. Please try again.",
    "paymentPendingMsg": "Your payment is under verification. We will update the status shortly.",
    "totalDonations": "Total Donations",
    "searchDonors": "Search donors by name, email, or transaction ID...",
    "filterStatus": "Filter Status",
    "allStatuses": "All Statuses",
    "dateAndTime": "Date & Time",
    "transactionId": "Transaction ID / Payment ID",
    "noDonations": "No donations found.",
    "donationsDashboardDesc": "Total contributions received from our generous donors",
    "numberDonations": "Number of Donations",
    "totalAmountDonated": "Total Amount Donated",
    "hanumanShlokaPart1": "Manojavam Marutatulyavegam, Jitendriyam Buddhimatam Varishtham.",
    "hanumanShlokaPart2": "Vatatmajam Vanarayuthamukhyam, Sriramadutam Sharanam Prapadye.",
    "purposeGeneral": "General Fund / General Seva",
    "purposeAnnadanam": "Hanuman Jayanthi Annadanam",
    "purposeRenovation": "Temple Devastanam Renovation",
    "purposeEducation": "Village Children Education Support",
    "bhimUpiQr": "BHIM UPI / QR",
    "upiApps": "GPay, PhonePe, Paytm",
    "creditDebitCard": "Credit / Debit Card",
    "cardBrands": "Visa, MasterCard, Rupay",
    "netBanking": "Net Banking",
    "bankList": "SBI, HDFC, ICICI, etc.",
    "signInTitle": "Sign In",
    "forgotPassword": "Forgot Password?",
    "passwordPlaceholder": "••••••••",
    "signInBtn": "Sign In",
    "signUpRedirectText": "New user?",
    "signUpRedirectLink": "Create an account",
    "mockAccountsText": "Mock Accounts Available:",
    "installAppBtn": "Install / Download App",
    "emailAddressLabel": "Email Address",
    "passwordLabel": "Password",
    "signUpTitle": "Register Account",
    "fullNameLabel": "Full Name",
    "fullNamePlaceholder": "Enter your full name",
    "phoneNumberLabel": "Phone Number",
    "phoneNumberPlaceholder": "+91 98765 43210",
    "villageAreaLabel": "Village / Area",
    "villageAreaPlaceholder": "e.g. Ramalayam Street, Zarugumalli",
    "confirmPasswordLabel": "Confirm Password",
    "signUpBtn": "Register Account",
    "signInRedirectText": "Already have an account?",
    "signInRedirectLink": "Sign In here",
    "continueWithGoogle": "Continue with Google",
    "signUpWithGoogle": "Sign up with Google",
    "or": "Or",
    "developedBy": "Developed by",
    "sendOtp": "Send OTP",
    "verifyOtp": "Verify OTP",
    "otpLabel": "Verification Code (OTP)",
    "eventsMeetings": "Events & Meetings",
    "eventsSubtitle": "Browse upcoming meetings, seva programs, and cultural festival celebrations",
    "addEvent": "Add Event",
    "completedActivities": "Completed Activities",
    "loadingEvents": "Loading events...",
    "noUpcomingEventsInLogs": "No upcoming events registered in our logs.",
    "noCompletedEventsInLogs": "No completed events registered in our logs.",
    "noEventsInLogs": "No events registered in our logs.",
    "editEventDetails": "Edit Event Details",
    "addNewEvent": "Add New Event",
    "eventTitle": "Event Title",
    "date": "Date",
    "time": "Time",
    "location": "Location",
    "description": "Description",
    "status": "Status",
    "upcoming": "Upcoming",
    "completed": "Completed",
    "saveEvent": "Save Event",
    "edit": "Edit",
    "delete": "Delete",
    "deleteEventConfirm": "Are you sure you want to delete this event? This action cannot be undone.",
    "expenditure": "Expenditure",
    "expenditureTitle": "Income & Expenditure Report",
    "expenditureSubtitle": "Transparent financial records of association funds, community seva, and temple renovation expenses.",
    "addExpense": "Add Expense",
    "totalExpense": "Total Expenses",
    "totalIncome": "Total Income / Donations",
    "netBalance": "Net Balance",
    "searchExpense": "Search by title, paid to, or notes...",
    "allCategories": "All Categories",
    "allMethods": "All Methods",
    "downloadReport": "Download Report",
    "expenseTitle": "Expense Title",
    "category": "Category",
    "amount": "Amount",
    "paidTo": "Paid To",
    "receipt": "Receipt",
    "actions": "Actions",
    "noExpensesFound": "No expenditure records found.",
    "saveExpense": "Save Expense",
    "editExpense": "Edit Expense",
    "catEventExpenses": "Event Expenses",
    "catDecoration": "Decoration",
    "catFood": "Food",
    "catTransport": "Transport",
    "catMaintenance": "Maintenance",
    "catDonationUsage": "Donation Usage",
    "catOtherExpenses": "Other Expenses",
    "methodCash": "Cash",
    "methodUpi": "UPI",
    "methodBankTransfer": "Bank Transfer",
    "methodCheque": "Cheque",
    "methodCard": "Card",
    "methodOther": "Other",
    "emailNotVerified": "Your email address is not verified.",
    "emailVerifyDesc": "Please click the link sent to your inbox, then click \\\"I Have Verified\\\" below.",
    "iHaveVerified": "I Have Verified",
    "resendLink": "Resend Link",
    "noUpcomingEvents": "No upcoming events scheduled right now. Check back soon!",
    "noRecentAnnouncements": "No recent announcements.",
    "noImagesUploaded": "No images uploaded yet.",
    "postedOn": "Posted on",
    "officeBearer": "Office Bearer",
    "memberRole": "Member Role",
    "detailsUpdated": "Details updated successfully!",
    "passwordUpdated": "Password updated successfully!",
    "notACommitteeMember": "Not a Committee Member",
    "notAdded": "Not added",
    "secureSsl": "Secure 256-Bit SSL Encryption",
    "donorDetails": "Donor Details",
    "amountPaid": "Amount Paid",
    "purpose": "Purpose",
    "makeAnotherDonation": "Make Another Donation",
    "returnToHome": "Return to Home",
    "divinePortalLogin": "Divine Portal Login",
    "emailOrPhone": "Email or Phone Number",
    "orContinueWith": "or continue with",
    "verifyYourAccount": "Verify Your Account",
    "step1Desc": "Step 1 of 2 — Fill Details",
    "step2Desc": "Step 2 of 2 — Enter OTP",
    "sendOtpTo": "Send OTP To",
    "phone": "Phone",
    "email": "Email",
    "sendOtpToPhone": "Send OTP to Phone",
    "sendOtpToEmail": "Send OTP to Email",
    "enter6DigitOtp": "Enter 6-Digit OTP",
    "changeDetails": "Change Details",
    "resendOtp": "Resend OTP",
    "resendIn": "Resend in",
    "verifyAndCreate": "Verify & Create Account",
    "aiAssistant": "Assistant",
    "onlineAskSeva": "Online - Ask about seva and events",
    "clearConversation": "Clear Conversation",
    "closeChat": "Close Chat",
    "howCanIHelp": "Welcome to Sri Anjaneya Youth Association. How can I help you today?",
    "aiTyping": "Anjaneya AI is typing...",
    "retry": "Retry",
    "suggestedQuestions": "Suggested Questions",
    "chatPlaceholder": "Ask a question about events, seva, etc...",
    "qWhatIsOrg": "What is Sri Anjaneya Youth?",
    "qUpcomingEvents": "What are the upcoming events?",
    "qSupportDonate": "How can I support & donate?",
    "qContactAssoc": "How to contact the association?",
    "openAlbum": "Open Album",
    "noImagesInAlbum": "No images in this album.",
    "downloadImage": "Download Image",
    "closeLightbox": "Close Lightbox",
    "imageFailedToLoad": "Image failed to load",
    "adminControlCenter": "Administrative Control Panel",
    "adminSubtitle": "Review statistics and manage registered portal users",
    "pendingRequests": "Pending Committee Membership Requests",
    "portalAccounts": "Portal Accounts",
    "verifiedDonations": "Verified Donations",
    "scheduledEvents": "Scheduled Events",
    "exportData": "Export Data",
    "manage": "Manage",
    "ledger": "Ledger",
    "noPhone": "No phone",
    "noArea": "No area",
    "approve": "Approve",
    "decline": "Decline",
    "makeAdmin": "Make Admin",
    "removeAdmin": "Remove Admin",
    "accessDenied": "Access Denied",
    "accessDeniedDesc": "You need admin privileges to view this page.",
    "loadingAdmin": "Loading Admin Database...",
    "userMember": "User / Member",
    "contactDetails": "Contact Details",
    "role": "Role",
    "committee": "Committee",
    "donor": "Donor",
    "method": "Method",
    "viewReceipt": "View Receipt",
    "noReceipt": "No receipt",
    "searchUsers": "Search users by name, email, or area...",
    "allRoles": "All Roles",
    "allPurposes": "All Purposes",
    "generalFund": "General Fund",
    "annadanam": "Hanuman Jayanthi Annadanam",
    "templeRenovation": "Temple Devastanam Renovation",
    "educationSupport": "Village Children Education Support",
    "totalUsers": "Total Users",
    "activeMembers": "Active Members",
    "membersCardList": "Members Card List",
    "contactUs": "Contact Us",
    "saving": "Saving...",
    "image": "Image",
    "available": "Available",
    "donationsLedger": "Donations Ledger",
    "galleryManagement": "Gallery Management",
    "registeredPortalAccounts": "Registered Portal Accounts",
    "refreshDatabase": "Refresh Database",
    "userDetails": "User Details",
    "village": "Village",
    "toggleRole": "Toggle Role",
    "noUsersFound": "No registered portal accounts found in database.",
    "approvedDonationsIncome": "Approved Donations (Income)",
    "approved": "approved",
    "pendingVerification": "Pending Verification",
    "pending": "pending",
    "rejectedDonations": "Rejected Donations",
    "rejected": "rejected",
    "searchDonationsPlaceholder": "Search donor name, phone, email, UTR...",
    "pendingOnly": "Pending Only",
    "approvedOnly": "Approved Only",
    "rejectedOnly": "Rejected Only",
    "exportCsv": "Export CSV",
    "contactInfo": "Contact Info",
    "sevaPurpose": "Seva Purpose",
    "receiptProof": "Receipt Proof",
    "transactionUtr": "Transaction / UTR",
    "view": "View",
    "addedToIncome": "Added to Income",
    "galleryAlbumManagement": "Gallery Album Management",
    "galleryAlbumDesc": "Create, edit, and delete photo albums displayed in the public gallery section.",
    "createNewAlbum": "Create New Album",
    "photos": "PHOTOS",
    "eventDate": "Event Date",
    "noAlbumsFound": "No gallery albums found. Click 'Create New Album' to get started.",
    "editGalleryAlbum": "Edit Gallery Album",
    "albumTitle": "Album Title",
    "shortDescription": "Short Description",
    "coverImage": "Cover Image",
    "chooseCoverImage": "Choose Cover Image",
    "albumImagesMultiple": "Album Images (Multiple)",
    "choosePhotos": "Choose Photos",
    "savingAlbum": "Saving Album...",
    "receiptVerification": "Payment Receipt Verification",
    "donationDate": "Donation Date",
    "utrPaymentRef": "UTR / Payment Ref",
    "workflowStatus": "Workflow Status",
    "donorMessage": "Donor Message",
    "close": "Close",
    "reject": "Reject",
    "approveAndAddToIncome": "Approve & Add to Income",
    "verifiedAndAddedToIncome": "Verified & Added to Income",
    "approveDonation": "Approve Donation"
},
  te: {
    "zarugumalli": "జరుగమల్లి",
    "websiteName": "శ్రీ ఆంజనేయ యూత్",
    "joinWebsiteName": "శ్రీ ఆంజనేయ యూత్ లో చేరండి",
    "associationSubtitle": "జరుగమల్లి యువజన సంఘం",
    "associationGallery": "సంఘం గ్యాలరీ",
    "gallerySubtitle": "మా సేవలు, పండుగలు మరియు ఆలయ కార్యక్రమాల దృశ్యాలు",
    "uploadPhoto": "ఫోటో అప్‌లోడ్ చేయి",
    "loadingGallery": "గ్యాలరీ లోడ్ అవుతోంది...",
    "noGalleryItems": "ఈ వర్గంలో గ్యాలరీ చిత్రాలు ఏవీ లేవు.",
    "uploadPhotoTitle": "సంఘం ఫోటోను అప్‌లోడ్ చేయి",
    "imagePresetLabel": "లేదా ఏదైనా భక్తి చిత్రాన్ని ఎంచుకోండి:",
    "categoryLabel": "వర్గం *",
    "captionLabel": "శీర్షిక / వివరణ *",
    "captionPlaceholder": "చిత్రం యొక్క వివరణను వ్రాయండి...",
    "savePhoto": "ఫోటో సేవ్ చేయి",
    "deletePhotoConfirm": "ఈ ఫోటోను గ్యాలరీ నుండి తొలగించాలనుకుంటున్నారా?",
    "failedDeletePhoto": "చిత్రాన్ని తొలగించడంలో విఫలమైంది.",
    "failedSavePhoto": "ఫోటోను సేవ్ చేయడంలో విఫలమైంది.",
    "fillAllDetails": "దయచేసి అన్ని వివరాలను పూరించండి.",
    "uploadedOn": "అప్‌లోడ్ చేసిన తేదీ",
    "templeEvents": "ఆలయ కార్యక్రమాలు",
    "festivals": "పండుగలు",
    "serviceSeva": "సేవా కార్యక్రమాలు",
    "galleryAlbums": "గ్యాలరీ ఆల్బమ్‌లు",
    "noGalleryAlbums": "గ్యాలరీ ఆల్బమ్‌లు ఏవీ కనుగొనబడలేదు.",
    "photosCount": "ఫోటోలు",
    "eventDateLabel": "కార్యక్రమ తేదీ *",
    "shortDescLabel": "చిన్న వివరణ *",
    "coverImageLabel": "కవర్ చిత్రం *",
    "albumImagesLabel": "ఆల్బమ్ చిత్రాలు",
    "saveAlbum": "ఆల్బమ్‌ను సేవ్ చేయండి",
    "createAlbum": "ఆల్బమ్ సృష్టించండి",
    "editAlbum": "ఆల్బమ్ సవరించు",
    "titleLabel": "గ్యాలరీ శీర్షిక *",
    "all": "అన్నీ",
    "committeeMembership": "కమిటీ సభ్యత్వం",
    "requestCommitteeBtn": "కమిటీ సభ్యత్వం కోసం అభ్యర్థించండి",
    "committeePendingStatus": "మీ అభ్యర్థన అడ్మిన్ ఆమోదం కోసం పెండింగ్‌లో ఉంది.",
    "committeeApprovedStatus": "మీరు ఆమోదించబడిన కమిటీ సభ్యులు!",
    "committeeRequestSent": "అభ్యర్థన విజయవంతంగా పంపబడింది!",
    "associationMembers": "సంఘ సభ్యులు",
    "dashboard": "డాష్‌బోర్డ్",
    "members": "సభ్యులు",
    "events": "కార్యక్రమాలు",
    "gallery": "గ్యాలరీ",
    "announcements": "ప్రకటనలు",
    "myProfile": "నా ప్రొఫైల్",
    "adminPanel": "అడ్మిన్ ప్యానెల్",
    "signOut": "లాగ్ అవుట్",
    "logout": "లాగ్ అవుట్",
    "jaiHanuman": "జై హనుమాన్",
    "welcome": "స్వాగతం",
    "bhaktha": "భక్తుడు",
    "youthMembers": "యువ సభ్యులు",
    "upcomingEvents": "రాబోయే కార్యక్రమాలు",
    "latestAnnouncements": "తాజా ప్రకటనలు",
    "viewAll": "అన్నీ చూడండి",
    "supportSeva": "మా సేవ & ఆలయ పునరుద్ధరణకు మద్దతు ఇవ్వండి",
    "copyUPI": "UPI ఐడీ కాపీ చేయి",
    "bankTransfer": "డైరెక్ట్ బ్యాంక్ బదిలీ",
    "galleryHighlights": "గ్యాలరీ ముఖ్యాంశాలు",
    "fullName": "పూర్తి పేరు",
    "roleDesignation": "హోదా / బాధ్యత",
    "phoneNumber": "ఫోన్ నంబర్",
    "villageArea": "గ్రామ ప్రాంతం / వీధి",
    "memberPhoto": "సభ్యుని ఫోటో",
    "chooseImage": "చిత్రాన్ని ఎంచుకోండి",
    "orUseUrl": "లేదా URL ఉపయోగించండి",
    "saveMember": "సభ్యుడిని సేవ్ చేయి",
    "cancel": "రద్దు చేయి",
    "editProfile": "ప్రొఫైల్ సవరించు",
    "password": "పాస్‌వర్డ్",
    "emailAddress": "ఈమెయిల్ చిరునామా",
    "contactNumber": "సంప్రదింపు సంఖ్య",
    "address": "చిరునామా / గ్రామం",
    "adminAccess": "అడ్మినిస్ట్రేటివ్ యాక్సెస్",
    "adminAccessDesc": "యాక్సెస్ ఉంది. మీరు డేటాబేస్ ఎంట్రీలను సవరించవచ్చు.",
    "newAnnouncement": "కొత్త ప్రకటన",
    "title": "శీర్షిక",
    "messageContent": "సందేశ కంటెంట్ *",
    "publishNow": "ప్రకటించు",
    "activeYouthDesc": "గ్రామ అభివృద్ధి కోసం పనిచేస్తున్న క్రియాశీల యువత",
    "importantUpdates": "యువతకు ముఖ్యమైన నవీకరణలు మరియు నోటీసులు",
    "addMemberBtn": "సభ్యుడిని చేర్చు",
    "editMemberDetails": "సభ్యుని వివరాలను సవరించు",
    "searchPlaceholder": "పేరు, బాధ్యత లేదా ప్రాంతం ద్వారా వెతకండి...",
    "noMembersFound": "వెతికిన దానికి సరిపోయే సభ్యులు ఎవరూ లేరు.",
    "publishAnnouncement": "ప్రకటనను ప్రచురించు",
    "notifications": "నోటిఫికేషన్లు",
    "noNotifications": "నోటిఫికేషన్‌లు లేవు.",
    "markAsRead": "చదివినట్లుగా గుర్తుపెట్టు",
    "viewAllNotifications": "అన్ని ప్రకటనలు చూడండి",
    "saveDetails": "వివరాలు సేవ్ చేయి",
    "choosePhoto": "ఫోటో ఎంచుకోండి",
    "remove": "తొలగించు",
    "jaiHanumanDesc": "“శ్రీ ఆంజనేయ యూత్ జరుగమల్లి” మన గ్రామంలో సేవ చేయడానికి, సంస్కృతిని కాపాడుకోవడానికి మరియు అభివృద్ధిని ప్రోత్సహించడానికి ఐక్యమైంది.",
    "sevaDesc": "ఉచిత అన్నదానాలు, విద్యా సామగ్రి పంపిణీ మరియు దేవాలయ ఉత్సవాలకు సహాయపడండి",
    "sevaLongDesc": "మేము క్రమం తప్పకుండా అన్నదానం, వెనుకబడిన విద్యార్థులకు విద్యా కిట్లు పంపిణీ చేయడం, రక్తదాన శిబిరాలు నిర్వహించడం మరియు శ్రీ ఆంజనేయ స్వామి ఆలయంలో ఉత్సవాల సమన్వయానికి సహాయం చేస్తుంటాము. మీ సహాయం ఈ మార్పునకు కారణమవుతుంది.",
    "newPassword": "కొత్త పాస్‌వర్డ్ (కనీసం 6 అక్షరాలు) *",
    "confirmNewPassword": "కొత్త పాస్‌వర్డ్ నిర్ధారించండి *",
    "updatePassword": "పాస్‌వర్డ్ నవీకరించు",
    "changePassword": "పాస్‌వర్డ్ మార్చు",
    "enterNewPassword": "కొత్త పాస్‌వర్డ్ నమోదు చేయండి",
    "confirmPasswordPlaceholder": "కొత్త పాస్‌వర్డ్ నిర్ధారించండి",
    "aboutUs": "మా గురించి",
    "quickLinks": "త్వరిత లింకులు",
    "footerCredits": "రూపకల్పన: గణేష్ నలమలపు",
    "footerRights": "అన్ని హక్కులు ప్రత్యేకించబడ్డాయి.",
    "footerTemple": "శ్రీ ఆంజనేయ స్వామి దేవస్థానం",
    "donationAlert": "విరాళం వివరాలు కాపీ చేయబడ్డాయి! UPI: anjaneyayouth@sbi",
    "loadingDashboard": "డాష్‌బోర్డ్ లోడ్ అవుతోంది...",
    "loadingAnnouncements": "ప్రకటనలు లోడ్ అవుతున్నాయి...",
    "loadingMembers": "సభ్యుల జాబితా లోడ్ అవుతోంది...",
    "redirectUrlLabel": "రీడైరెక్ట్ లింక్ (ఐచ్ఛికం)",
    "redirectUrlPlaceholder": "https://example.com/more-info లేదా వీడియో లింక్",
    "aboutUsTitle": "మా సంఘం గురించి",
    "aboutPara1": "జరుగమల్లి గ్రామ ఉత్సాహవంతులైన యువకులు స్థాపించిన ఈ సంఘం, శ్రీ ఆంజనేయ స్వామి వారి ఆశీస్సులతో సేవలను అందిస్తోంది.",
    "aboutPara2": "మా ప్రధాన లక్ష్యం మూడు స్తంభాలపై ఆధారపడి ఉంటుంది: సేవ (సామాజిక సేవ), సంస్కృతి (సాంప్రదాయ ఉత్సవాల పరిరక్షణ), మరియు సంఘం (సమైక్యతను పెంపొందించడం మరియు గ్రామ అభివృద్ధికి తోడ్పడడం).",
    "aboutPara3": "మేము గ్రామంలో పరిశుభ్రత కార్యక్రమాలు, స్థానిక పండుగల ఊరేగింపులు, అత్యవసర సేవలు మరియు దేవాలయ ఉత్సవాలలో సహాయం చేయడం వంటి నిరంతర కార్యక్రమాలను నిర్వహిస్తాము.",
    "reachUsTitle": "మమ్మల్ని సంప్రదించండి",
    "officeAddressLabel": "కార్యాలయ చిరునామా",
    "officeAddressVal": "శ్రీ ఆంజనేయ యూత్ హాల్, రామాలయం గుడి దగ్గర, జరుగమల్లి గ్రామం, ప్రకాశం జిల్లా, ఆంధ్రప్రదేశ్ - 523274",
    "callCoordinatorLabel": "ప్రెసిడెంట్ / కోఆర్డినేటర్‌ను సంప్రదించండి",
    "emailSupportLabel": "ఈమెయిల్ మద్దతు",
    "contactAssociation": "సంఘాన్ని సంప్రదించండి",
    "footerAddressVal": "శ్రీ ఆంజనేయ యూత్ అసోసియేషన్, జరుగమల్లి గ్రామం, ప్రకాశం జిల్లా, ఆంధ్రప్రదేశ్ - 523274",
    "unitedQuote": "సేవ, సంస్కృతి మరియు సమాజం కోసం ఐక్యమయ్యాము",
    "donate": "విరాళం ఇవ్వండి",
    "donations": "విరాళాలు",
    "donorName": "దాత పేరు *",
    "donorNamePlaceholder": "మీ పూర్తి పేరు నమోదు చేయండి",
    "mobileNumber": "మొబైల్ సంఖ్య *",
    "mobileNumberPlaceholder": "10 అంకెల మొబైల్ సంఖ్యను నమోదు చేయండి",
    "emailAddressOptional": "ఈమెయిల్ చిరునామా (ఐచ్ఛికం)",
    "emailAddressPlaceholder": "name@domain.com",
    "donationAmount": "విరాళం మొత్తం (₹) *",
    "donationAmountPlaceholder": "విరాళం మొత్తం నమోదు చేయండి",
    "paymentMethod": "చెల్లింపు విధానం *",
    "selectMethod": "చెల్లింపు విధానాన్ని ఎంచుకోండి",
    "donationPurpose": "విరాళం యొక్క ఉద్దేశం / సందేశం",
    "donationPurposePlaceholder": "ఉదా: అన్నదానం, ఆలయ పునరుద్ధరణ, సాధారణ నిధి",
    "donateNowBtn": "ఇప్పుడే విరాళం ఇవ్వండి",
    "paymentSuccess": "చెల్లింపు విజయవంతమైంది",
    "paymentFailed": "చెల్లింపు విఫలమైంది",
    "paymentPending": "చెల్లింపు పెండింగ్‌లో ఉంది",
    "thankYouDonation": "మీ ఉదార విరాళానికి ధన్యవాదాలు! శ్రీ ఆంజనేయ స్వామి వారి ఆశీస్సులు మీకు ఎల్లప్పుడూ ఉండాలని కోరుకుంటున్నాము.",
    "paymentErrorMsg": "మీ లావాదేవీని పూర్తి చేయలేకపోయాము. దయచేసి మళ్లీ ప్రయత్నించండి.",
    "paymentPendingMsg": "మీ చెల్లింపు ధృవీకరణలో ఉంది. మేము త్వరలో స్థితిని నవీకరిస్తాము.",
    "totalDonations": "మొత్తం విరాళాలు",
    "searchDonors": "దాత పేరు, ఈమెయిల్ లేదా లావాదేవీ ID ద్వారా వెతకండి...",
    "filterStatus": "చెల్లింపు స్థితి ఫిల్టర్",
    "allStatuses": "అన్ని స్థితులు",
    "dateAndTime": "తేదీ & సమయం",
    "transactionId": "లావాదేవీ ID / చెల్లింపు ID",
    "noDonations": "విరాళాలు ఏవీ లేవు.",
    "donationsDashboardDesc": "మా దాతల నుండి సేకరించిన మొత్తం విరాళాలు",
    "numberDonations": "విరాళాల సంఖ్య",
    "totalAmountDonated": "మొత్తం సేకరించిన విరాళాలు",
    "hanumanShlokaPart1": "మనోజవం మారుతతుల్యవేగం, జితేంద్రియం బుద్ధిమతాం వరిష్ఠమ్.",
    "hanumanShlokaPart2": "వాతాత్మజం వానరయూథముఖ్యం, శ్రీరామదూతం శరణం ప్రపద్యే.",
    "purposeGeneral": "సాధారణ నిధి / సాధారణ సేవ",
    "purposeAnnadanam": "హనుమాన్ జయంతి అన్నదానం",
    "purposeRenovation": "దేవాలయ పునరుద్ధరణ",
    "purposeEducation": "గ్రామ పిల్లల విద్యా సహాయం",
    "bhimUpiQr": "BHIM UPI / QR కోడ్",
    "upiApps": "GPay, PhonePe, Paytm",
    "creditDebitCard": "క్రెడిట్ / డెబిట్ కార్డ్",
    "cardBrands": "వీసా, మాస్టర్ కార్డ్, రూపే",
    "netBanking": "నెట్ బ్యాంకింగ్",
    "bankList": "SBI, HDFC, ICICI, మొదలైనవి",
    "signInTitle": "లాగిన్",
    "forgotPassword": "పాస్‌వర్డ్ మర్చిపోయారా?",
    "passwordPlaceholder": "••••••••",
    "signInBtn": "లాగిన్ చేయి",
    "signUpRedirectText": "కొత్త యూజరా?",
    "signUpRedirectLink": "ఖాతాను సృష్టించండి",
    "mockAccountsText": "డెమో ఖాతాల వివరాలు:",
    "installAppBtn": "యాప్ డౌన్‌లోడ్ చేయండి",
    "emailAddressLabel": "ఈమెయిల్ చిరునామా",
    "passwordLabel": "పాస్‌వర్డ్",
    "signUpTitle": "ఖాతాను సృష్టించండి",
    "fullNameLabel": "పూర్తి పేరు",
    "fullNamePlaceholder": "మీ పూర్తి పేరు నమోదు చేయండి",
    "phoneNumberLabel": "ఫోన్ నంబర్",
    "phoneNumberPlaceholder": "+91 98765 43210",
    "villageAreaLabel": "గ్రామం / ప్రాంతం",
    "villageAreaPlaceholder": "ఉదా: రామాలయం వీధి, జరుగమల్లి",
    "confirmPasswordLabel": "పాస్‌వర్డ్ నిర్ధారించండి",
    "signUpBtn": "నమోదు చేయి",
    "signInRedirectText": "ఇప్పటికే ఖాతా ఉందా?",
    "signInRedirectLink": "ఇక్కడ లాగిన్ అవ్వండి",
    "continueWithGoogle": "Google తో లాగిన్ అవ్వండి",
    "signUpWithGoogle": "Google తో సైన్ అప్ అవ్వండి",
    "or": "లేదా",
    "developedBy": "రూపకల్పన:",
    "sendOtp": "OTP పంపండి",
    "verifyOtp": "OTP ధృవీకరించండి",
    "otpLabel": "ధృవీకరణ కోడ్ (OTP)",
    "eventsMeetings": "కార్యక్రమాలు & సమావేశాలు",
    "eventsSubtitle": "రాబోయే సమావేశాలు, సేవా కార్యక్రమాలు మరియు సాంస్కృతిక ఉత్సవాల వివరాలు",
    "addEvent": "కార్యక్రమాన్ని జోడించు",
    "completedActivities": "పూర్తయిన కార్యక్రమాలు",
    "loadingEvents": "కార్యక్రమాలు లోడ్ అవుతున్నాయి...",
    "noUpcomingEventsInLogs": "లాగ్‌లలో రాబోయే కార్యక్రమాలు ఏవీ నమోదు కాలేదు.",
    "noCompletedEventsInLogs": "లాగ్‌లలో పూర్తయిన కార్యక్రమాలు ఏవీ లేవు.",
    "noEventsInLogs": "లాగ్‌లలో ఎలాంటి కార్యక్రమాలు నమోదు కాలేదు.",
    "editEventDetails": "కార్యక్రమ వివరాలు సవరించు",
    "addNewEvent": "కొత్త కార్యక్రమాన్ని జోడించు",
    "eventTitle": "కార్యక్రమ శీర్షిక",
    "date": "తేదీ",
    "time": "సమయం",
    "location": "స్థలం",
    "description": "వివరణ",
    "status": "స్థితి",
    "upcoming": "రాబోయేవి",
    "completed": "పూర్తయినవి",
    "saveEvent": "కార్యక్రమాన్ని సేవ్ చేయి",
    "edit": "సవరించు",
    "delete": "తొలగించు",
    "deleteEventConfirm": "మీరు ఖచ్చితంగా ఈ కార్యక్రమాన్ని తొలగించాలనుకుంటున్నారా? ఈ చర్యను రద్దు చేయలేరు.",
    "expenditure": "ఖర్చులు",
    "expenditureTitle": "ఆదాయ & వ్యయాల నివేదిక",
    "expenditureSubtitle": "సంఘ నిధుల నిర్వహణ, సేవలు మరియు దేవాలయ పునరుద్ధరణ ఖర్చుల పారదర్శక నివేదిక.",
    "addExpense": "ఖర్చును నమోదు చేయి",
    "totalExpense": "మొత్తం ఖర్చులు",
    "totalIncome": "మొత్తం ఆదాయం / విరాళాలు",
    "netBalance": "నికర బ్యాలెన్స్",
    "searchExpense": "శీర్షిక, చెల్లించిన వ్యక్తి ద్వారా వెతకండి...",
    "allCategories": "అన్ని వర్గాలు",
    "allMethods": "అన్ని చెల్లింపు మార్గాలు",
    "downloadReport": "నివేదిక డౌన్‌లోడ్ చేయి",
    "expenseTitle": "ఖర్చు శీర్షిక",
    "category": "వర్గం",
    "amount": "మొత్తం",
    "paidTo": "ఎవరికి చెల్లించారు",
    "receipt": "రసీదు",
    "actions": "చర్యలు",
    "noExpensesFound": "ఎలాంటి ఖర్చు వివరాలు కనుగొనబడలేదు.",
    "saveExpense": "ఖర్చును సేవ్ చేయి",
    "editExpense": "ఖర్చు వివరాలు సవరించు",
    "catEventExpenses": "కార్యక్రమ ఖర్చులు",
    "catDecoration": "అలంకరణ",
    "catFood": "భోజన / అన్నదానం",
    "catTransport": "రవాణా",
    "catMaintenance": "నిర్వహణ",
    "catDonationUsage": "విరాళాల వినియోగం",
    "catOtherExpenses": "ఇతర ఖర్చులు",
    "methodCash": "నగదు",
    "methodUpi": "UPI",
    "methodBankTransfer": "బ్యాంక్ బదిలీ",
    "methodCheque": "చెక్",
    "methodCard": "కార్డ్",
    "methodOther": "ఇతరములు",
    "emailNotVerified": "మీ ఈమెయిల్ చిరునామా ధృవీకరించబడలేదు.",
    "emailVerifyDesc": "దయచేసి మీ ఇన్‌బాక్స్‌కు పంపిన లింక్‌ను క్లిక్ చేసి, క్రింద \\\"ధృవీకరించాను\\\" బటన్ నొక్కండి.",
    "iHaveVerified": "నేను ధృవీకరించాను",
    "resendLink": "లింక్ మళ్లీ పంపు",
    "noUpcomingEvents": "ప్రస్తుతానికి రాబోయే కార్యక్రమాలు ఏవీ లేవు. త్వరలో తనిఖీ చేయండి!",
    "noRecentAnnouncements": "తాజా ప్రకటనలు ఏవీ లేవు.",
    "noImagesUploaded": "చిత్రాలు ఏవీ అప్‌లోడ్ చేయలేదు.",
    "postedOn": "ప్రచురించిన తేదీ:",
    "officeBearer": "కార్యవర్గ సభ్యుడు",
    "memberRole": "సభ్యుని హోదా",
    "detailsUpdated": "వివరాలు విజయవంతంగా నవీకరించబడ్డాయి!",
    "passwordUpdated": "పాస్‌వర్డ్ విజయవంతంగా నవీకరించబడింది!",
    "notACommitteeMember": "కమిటీ సభ్యులు కాదు",
    "notAdded": "జోడించలేదు",
    "secureSsl": "సురక్షితమైన 256-బిట్ SSL ఎన్‌క్రిప్షన్",
    "donorDetails": "దాత వివరాలు",
    "amountPaid": "చెల్లించిన మొత్తం",
    "purpose": "ఉద్దేశం",
    "makeAnotherDonation": "మరో విరాళం ఇవ్వండి",
    "returnToHome": "హోమ్‌కు తిరిగి వెళ్లండి",
    "divinePortalLogin": "సభ్యుల లాగిన్",
    "emailOrPhone": "ఈమెయిల్ లేదా ఫోన్ నంబర్",
    "orContinueWith": "లేదా వీటితో కొనసాగించండి",
    "verifyYourAccount": "మీ ఖాతాను ధృవీకరించండి",
    "step1Desc": "దశ 1/2 — వివరాలను పూరించండి",
    "step2Desc": "దశ 2/2 — OTP నమోదు చేయండి",
    "sendOtpTo": "OTP పంపవలసిన మార్గం",
    "phone": "ఫోన్",
    "email": "ఈమెయిల్",
    "sendOtpToPhone": "ఫోన్‌కు OTP పంపండి",
    "sendOtpToEmail": "ఈమెయిల్‌కు OTP పంపండి",
    "enter6DigitOtp": "6 అంకెల OTP నమోదు చేయండి",
    "changeDetails": "వివరాలు మార్చండి",
    "resendOtp": "OTP మళ్లీ పంపండి",
    "resendIn": "మళ్లీ పంపే సమయం",
    "verifyAndCreate": "ధృవీకరించి ఖాతాను సృష్టించండి",
    "aiAssistant": "సహాయకుడు",
    "onlineAskSeva": "ఆన్‌లైన్ - సేవ మరియు కార్యక్రమాల గురించి అడగండి",
    "clearConversation": "సంభాషణను క్లియర్ చేయి",
    "closeChat": "చాట్ మూసివేయి",
    "howCanIHelp": "శ్రీ ఆంజనేయ యూత్ అసోసియేషన్‌కు స్వాగతం. ఈరోజు మీకు ఎలా సహాయపడగలను?",
    "aiTyping": "ఆంజనేయ AI సమాధానం టైప్ చేస్తోంది...",
    "retry": "మళ్లీ ప్రయత్నించండి",
    "suggestedQuestions": "సూచించిన ప్రశ్నలు",
    "chatPlaceholder": "కార్యక్రమాలు, సేవల గురించి ప్రశ్న అడగండి...",
    "qWhatIsOrg": "శ్రీ ఆంజనేయ యూత్ అంటే ఏమిటి?",
    "qUpcomingEvents": "రాబోయే కార్యక్రమాలు ఏమిటి?",
    "qSupportDonate": "విరాళం ఎలా ఇవ్వాలి?",
    "qContactAssoc": "సంఘాన్ని ఎలా సంప్రదించాలి?",
    "openAlbum": "ఆల్బమ్ చూడండి",
    "noImagesInAlbum": "ఈ ఆల్బమ్‌లో చిత్రాలు ఏవీ లేవు.",
    "downloadImage": "చిత్రాన్ని డౌన్‌లోడ్ చేయి",
    "closeLightbox": "మూసివేయి",
    "imageFailedToLoad": "చిత్రం లోడ్ కాలేదు",
    "adminControlCenter": "అడ్మినిస్ట్రేటివ్ కంట్రోల్ ప్యానెల్",
    "adminSubtitle": "గణాంకాలను సమీక్షించండి మరియు పోర్టల్ సభ్యులను నిర్వహించండి",
    "pendingRequests": "పెండింగ్ కమిటీ సభ్యత్వ అభ్యర్థనలు",
    "portalAccounts": "పోర్టల్ ఖాతాలు",
    "verifiedDonations": "ధృవీకరించబడిన విరాళాలు",
    "scheduledEvents": "రాబోయే కార్యక్రమాలు",
    "exportData": "డేటా ఎగుమతి చేయి",
    "manage": "నిర్వహించు",
    "ledger": "ఖాతా వివరాలు",
    "noPhone": "ఫోన్ లేదు",
    "noArea": "ప్రాంతం లేదు",
    "approve": "ఆమోదించు",
    "decline": "తిరస్కరించు",
    "makeAdmin": "అడ్మిన్‌గా నియమించు",
    "removeAdmin": "అడ్మిన్ హోదా తొలగించు",
    "accessDenied": "యాక్సెస్ నిరాకరించబడింది",
    "accessDeniedDesc": "ఈ పేజీని చూడటానికి మీకు అడ్మిన్ అనుమతులు అవసరం.",
    "loadingAdmin": "అడ్మిన్ డేటాబేస్ లోడ్ అవుతోంది...",
    "userMember": "వినియోగదారుడు / సభ్యుడు",
    "contactDetails": "సంప్రదింపు వివరాలు",
    "role": "హోదా",
    "committee": "కమిటీ",
    "donor": "దాత",
    "method": "చెల్లింపు విధానం",
    "viewReceipt": "రసీదు చూడండి",
    "noReceipt": "రసీదు లేదు",
    "searchUsers": "పేరు, ఈమెయిల్ లేదా ప్రాంతం ద్వారా వెతకండి...",
    "allRoles": "అన్ని హోదాలు",
    "allPurposes": "అన్ని ఉద్దేశాలు",
    "generalFund": "సాధారణ నిధి",
    "annadanam": "హనుమాన్ జయంతి అన్నదానం",
    "templeRenovation": "దేవాలయ పునరుద్ధరణ",
    "educationSupport": "గ్రామ పిల్లల విద్యా సహాయం",
    "totalUsers": "మొత్తం సభ్యులు",
    "activeMembers": "క్రియాశీల సభ్యులు",
    "membersCardList": "సభ్యుల కార్డు జాబితా",
    "contactUs": "మమ్మల్ని సంప్రదించండి",
    "saving": "సేవ్ అవుతోంది...",
    "image": "చిత్రం",
    "available": "అందుబాటులో ఉంది",
    "donationsLedger": "విరాళాల రికార్డు",
    "galleryManagement": "గ్యాలరీ నిర్వహణ",
    "registeredPortalAccounts": "నమోదైన పోర్టల్ ఖాతాలు",
    "refreshDatabase": "డేటాబేస్ రిఫ్రెష్ చేయండి",
    "userDetails": "వినియోగదారు వివరాలు",
    "village": "గ్రామం",
    "toggleRole": "హోదా మార్చండి",
    "noUsersFound": "డేటాబేస్‌లో నమోదైన పోర్టల్ ఖాతాలు ఏవీ లేవు.",
    "approvedDonationsIncome": "ఆమోదించబడిన విరాళాలు (ఆదాయం)",
    "approved": "ఆమోదించబడింది",
    "pendingVerification": "ధృవీకరణ పెండింగ్‌లో ఉంది",
    "pending": "పెండింగ్",
    "rejectedDonations": "తిరస్కరించబడిన విరాళాలు",
    "rejected": "తిరస్కరించబడింది",
    "searchDonationsPlaceholder": "దాత పేరు, ఫోన్, ఈమెయిల్, UTR ద్వారా వెతకండి...",
    "pendingOnly": "పెండింగ్ మాత్రమే",
    "approvedOnly": "ఆమోదించబడినవి మాత్రమే",
    "rejectedOnly": "తిరస్కరించబడినవి మాత్రమే",
    "exportCsv": "CSV ఎగుమతి చేయి",
    "contactInfo": "సంప్రదింపు సమాచారం",
    "sevaPurpose": "సేవా ఉద్దేశం",
    "receiptProof": "రసీదు రుజువు",
    "transactionUtr": "లావాదేవీ / UTR",
    "view": "చూడండి",
    "addedToIncome": "ఆదాయానికి చేర్చబడింది",
    "galleryAlbumManagement": "గ్యాలరీ ఆల్బమ్ నిర్వహణ",
    "galleryAlbumDesc": "పబ్లిక్ గ్యాలరీ విభాగంలో ప్రదర్శించబడే ఫోటో ఆల్బమ్‌లను సృష్టించండి, సవరించండి మరియు తొలగించండి.",
    "createNewAlbum": "కొత్త ఆల్బమ్ సృష్టించండి",
    "photos": "ఫోటోలు",
    "eventDate": "కార్యక్రమం తేదీ",
    "noAlbumsFound": "గ్యాలరీ ఆల్బమ్‌లు ఏవీ కనుగొనబడలేదు. ప్రారంభించడానికి 'కొత్త ఆల్బమ్ సృష్టించండి' క్లిక్ చేయండి.",
    "editGalleryAlbum": "గ్యాలరీ ఆల్బమ్‌ను సవరించండి",
    "albumTitle": "ఆల్బమ్ శీర్షిక",
    "shortDescription": "సంక్షిప్త వివరణ",
    "coverImage": "కవర్ చిత్రం",
    "chooseCoverImage": "కవర్ చిత్రాన్ని ఎంచుకోండి",
    "albumImagesMultiple": "ఆల్బమ్ చిత్రాలు (బహుళ)",
    "choosePhotos": "ఫోటోలను ఎంచుకోండి",
    "savingAlbum": "ఆల్బమ్ సేవ్ అవుతోంది...",
    "receiptVerification": "చెల్లింపు రసీదు ధృవీకరణ",
    "donationDate": "విరాళం తేదీ",
    "utrPaymentRef": "UTR / చెల్లింపు సూచన",
    "workflowStatus": "పరిశీలన స్థితి",
    "donorMessage": "దాత సందేశం",
    "close": "మూసివేయి",
    "reject": "తిరస్కరించు",
    "approveAndAddToIncome": "ఆమోదించి ఆదాయానికి చేర్చండి",
    "verifiedAndAddedToIncome": "ధృవీకరించబడింది మరియు ఆదాయానికి చేర్చబడింది",
    "approveDonation": "విరాళాన్ని ఆమోదించండి"
}
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('sa_language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('sa_language', language);
    // Dynamically update html lang attribute
    document.documentElement.lang = language;
    // Dynamically update document/tab title in Telugu/English
    document.title = language === 'en' 
      ? 'Sri Anjaneya Youth Zarugumalli' 
      : 'శ్రీ ఆంజనేయ యూత్ జరుగమల్లి';
  }, [language]);

  /**
   * Enhanced translation lookup:
   * 1. Returns localized dictionary entry if key exists
   * 2. If language is 'te' and key/text is not in dictionary,
   *    passes it to translateText() to translate phrases, roles, or transliterate names.
   */
  const t = (keyOrText, fallback) => {
    if (!keyOrText) return '';
    if (translations[language]?.[keyOrText]) {
      return translations[language][keyOrText];
    }
    if (translations['en']?.[keyOrText]) {
      if (language === 'te') {
        return translateText(translations['en'][keyOrText], 'te');
      }
      return translations['en'][keyOrText];
    }
    // Direct English string passed into t()
    if (language === 'te') {
      return translateText(keyOrText, 'te');
    }
    return fallback !== undefined ? fallback : keyOrText;
  };

  const contextValue = {
    language,
    setLanguage,
    t,
    // Context-bound helper functions that automatically use current language
    translateName: (name) => translateName(name, language),
    translateRole: (role) => translateRole(role, language),
    translateAddress: (addr) => translateAddress(addr, language),
    translateStatus: (status) => translateStatus(status, language),
    translatePurpose: (purpose) => translatePurpose(purpose, language),
    translateText: (txt) => translateText(txt, language),
  };

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
